gta4xl-common: Switch data to use F2FS
I've noticed that Samsung's stock firmware uses F2FS for data, while
this tree has been setup to use EXT4 from the start.

Switch to F2FS. Later changes for encryption upgrades will require data
to be formatted anyway, so might as well.

While at it, explicitly specify the system image filesystem as EXT4,
since otherwise, this build error occurs on system image generation
without TARGET_USERIMAGES_USE_EXT4 set:
build_image.BuildImageError: Error: unknown filesystem type:

Change-Id: Idf01a6db4f911381590e57d268e332a7202418e7